name: uzmobile
description: A new Flutter application.

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  rxdart: ^0.27.1
  url_launcher: ^6.0.7
  share: ^2.0.4
  sqflite: ^2.0.0+3
  http: ^0.13.3
  easy_localization: 3.0.0
  path: ^1.8.0
  flutter_phone_direct_caller: ^2.0.0
#  flutter_automation: ^2.0.0
  launch_review: ^2.0.0
#  webview_flutter_plus: ^0.1.1+9
#  html: ^0.14.0+3
  flutter_html: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_rename_app: ^1.0.0
  flutter_launcher_icons: ^0.9.0

#flutter_rename_app:
#  application_name: Uzmobile
#  dart_package_name: uzmobile
#  application_id: uz.uzmobile.helper
#  bundle_id: uz.uzmobile.helper
#  android_package_name: uz.uzmobile.helper
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icon/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
